  name: Latest INSiDER - Dentro la Tecnologia Episodes
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest episodes from INSiDER - Dentro la Tecnologia
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "INSIDER"
          feed_list: "https://www.dentrolatecnologia.it/rss"